### ISSUE TITLE
Problem with setting variable to any value

### ISSUE THREAD

**Issue by dimityrivanov** [editfmah/sharkorm#31] opened 2016-09-18 07:39 UTC
Hello All,

I have followed the getting started tutorial but I am experiencing the following error 👍 
When I create object like person and later on I want to set its name and age they are never set they stay nil , but if I remove the class SRKObject from my object I can set the variables perfectlly fine.
Also I found out that if I hava a constructor that set the variables and after that call super.init() set the variables as well but why my first case isn't working ?

**Comment by editfmah** [comment] 2016-09-18 07:52
Hi,

Starting with your second problem, this is a bug in swift and has been reported to Apple (a radar has been opened), see here:

[http://stackoverflow.com/questions/37623385/timing-issues-with-swift-class-with-dynamic-variable-which-inherits-from-object](http://stackoverflow.com/questions/37623385/timing-issues-with-swift-class-with-dynamic-variable-which-inherits-from-object)

Basically, when a swift object inherits from an Objective-c object and the +initialize method creates the get/set methods for it, then the values you set within the init() function get lost.

Although very frustrating, you can always set these values later, once .init() has completed and it will work perfectly.

For your initial problem:

Can you confirm whether, when you commit the object, if the values get persisted into the database?  Because there is also another bug in LLDB where the values look like nil in the browser, but when you **po person.forename**, it works.

If you could let me know if the properties make it into the database file or not, and if not, if you could create an object, set some properties, and then post here the definition and a **po** from the debugger.

Thanks
Adrian

**Comment by dimityrivanov** [comment] 2016-09-18 08:00
@editfmah Hi
I can confirm this bug as well on my side I just find out before reading this that the browser show the values as nil but when I get the property value it is the correct one I saved. (strange things).

Also I can confirm that the property made it to the database

Any idea when those gonna be fixed ?

Regards,
Mitko

**Comment by editfmah** [comment] 2016-09-18 08:22
Excellent, 

This is definitely a bug in LLDB & XCode, but we will try to find a way to work around it, because it is very frustrating.   We will also implement an init method for SRKObjects which will allow you to populate an object with values from the start.  This might go a small way towards minimising the frustrations of this bug.

Thanks,
Adrian

**Comment by editfmah** [comment] 2016-10-22 22:09
Closing this as it's a duplicate of a another request.

**Closed as completed by editfmah** 2016-10-22 22:09 UTC
Labels: bug, help wanted

**Comment by mattvb91** [comment] 2017-02-12 15:19
Just want to chip in I've spent the last 2 days on the exact same issue just to find out like above the values are actually set but when viewing them in the debugger they are all set to nil! Very annoying. 

@editfmah can you reference the open duplicate issue? Thanks!

Just so others can find this here are some search terms I used:
sharkorm dynamic var nil
swift not setting dynamic object var

**Comment by editfmah** [comment] 2017-02-12 16:43
Hi @mattvb91 

https://github.com/sharksync/sharkorm/issues/24 is the other place this is raised, but the problem does not happen in the new swift version of the ORM, as this is a problem with Swift being unable to inspect Obj-C classes where the methods have been swizzled.

Basically, if the *Mirror* inspection doesn't work then you don't see any values.

Sorry for any inconvenience, we will look to see if we can just trick LLDB into displaying the values as opposed to fixing it "properly".

Thanks
Adrian
